apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  namespace: microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      service: checkoutservice
  template:
    metadata:
      labels:
        service: checkoutservice
    spec:
      containers:
      - name: checkoutservice
        image: checkoutservice
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
        resources:
          limits:
            cpu: "200m"
            memory: "128Mi"
          requests:
            cpu: "100m"
            memory: "64Mi"
        env:
        - name: PORT
          value: "5050"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice:3550"
        - name: SHIPPING_SERVICE_ADDR
          value: "shippingservice:50051"
        - name: PAYMENT_SERVICE_ADDR
          value: "paymentservice:50051"
        - name: EMAIL_SERVICE_ADDR
          value: "emailservice:5000"
        - name: CURRENCY_SERVICE_ADDR
          value: "currencyservice:7000"
        - name: CART_SERVICE_ADDR
          value: "cartservice:7070"  

---
kind: Service
apiVersion: v1
metadata:
  name:  checkoutservice
  namespace: microservice
spec:
  selector:
    service: checkoutservice
  type:  ClusterIP 
  ports:
  - name:  checkoutservice-port
    port:  5050
    targetPort:  5050
