apiVersion: apps/v1
kind: Deployment
metadata:
  name:  currencyservice
  namespace: microservice
  labels:
    service:  currencyservice
spec:
  selector:
    matchLabels:
      service:  currencyservice
  template:
    metadata:
      labels:
        service:  currencyservice
    spec:
      containers:
      - image:  currencyservice
        name:  currencyservice
        imagePullPolicy: Never
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
          limits:
            cpu: "100m"
            memory: "100M"
        env:
        - name: PORT
          value: "7000"
        - name: DISABLE_PROFILER
          value: "1"       
        ports:
        - containerPort:  7000
          name:  currencyservice
---
kind: Service
apiVersion: v1
metadata:
  name:  currencyservice
  namespace: microservice
spec:
  selector:
    service:  currencyservice
  type:  ClusterIP 
  ports:
  - name:  grpc
    port:  7000
    targetPort:  7000