apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  namespace: microservice
  labels:
    service: emailservice
spec:
  selector:
    matchLabels:
      service: emailservice
  template:
    metadata:
      labels:
        service: emailservice
    spec:
      containers:
      - image: emailservice
        name: emailservice
        imagePullPolicy: Never
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
          limits:
            cpu: "100m"
            memory: "100M"
        env:
        - name: PORT
          value: "8080"
        - name: DISABLE_PROFILER
          value: "1"       
        ports:
        - containerPort:  8080
          name: emailservice
---
kind: Service
apiVersion: v1
metadata:
  name: emailservice
  namespace: microservice
spec:
  selector:
    service: emailservice
  type:  ClusterIP 
  ports:
  - name: emailservice
    port:  5000
    targetPort:  8080