apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
  namespace: microservice
  labels:
    service: recommendationservice
spec:
  selector:
    matchLabels:
      service: recommendationservice
  template:
    metadata:
      labels:
        service: recommendationservice
    spec:
      containers:
      - image: recommendationservice
        name: recommendationservice
        imagePullPolicy: Never
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
          limits:
            cpu: "100m"
            memory: "100M"
        env:
        - name: PORT
          value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice:3550"
        - name: DISABLE_PROFILER
          value: "1"       
        ports:
        - containerPort:  8080
          name: recommendation
---
kind: Service
apiVersion: v1
metadata:
  name: recommendationserviceport
  namespace: microservice
spec:
  selector:
    service: recommendationservice
  type:  ClusterIP 
  ports:
  - name: recommendationserviceport
    port:  8080
    targetPort:  8080